FUNC_BASIC(ADD, "+")
FUNC_BASIC(SUB, "-")
FUNC_BASIC(MUL, "*")
FUNC_BASIC(DIV, "/")
FUNC_BASIC(POW, "^")

FUNC(LN,  "ln")
FUNC(SIN, "sin")
FUNC(SH,  "sinh")
FUNC(CH,  "cosh")
FUNC(TH,  "tanh")

FUNC(COS, "cos")
FUNC(TAN, "tan")
FUNC(COT, "cot")
FUNC(ASH, "arcsinh")
FUNC(ACH, "arccosh")
FUNC(ATH, "arctanh")
FUNC(ABS, "abs")

FUNC(ASIN, "arcsin")
FUNC(ACOS, "arccos")
FUNC(ATAN, "arctan")
FUNC(ACOT, "arccot")
FUNC(ACTH, "arccoth")
FUNC(SQRT, "sqrt")
